### ISSUE TITLE
Release with updated lxml dep

### ISSUE THREAD

**Issue by nsoranzo** [twill-tools/twill#23]
Hi,
I'm working on adding Python 3.13 support to an application that depends on Twill, it would be nice if you could make a release that include https://github.com/twill-tools/twill/commit/43fb4597b92387944e95a10c87c324818bfe0b1c .

Thanks!

**Comment by Cito** [comment]
Released as version 3.2.5 now.

Unfortunately, I cannot guarantee full Python 3.13 compatibility yet since it is still in beta (so things might break) and the tests need Quixote which does not support it. ~But I plan to replace Quixote and create a version that officially supports Python 3.13 as soon as it's released.~ Update: Quixote has now been replaced by Flask.

**Comment by nsoranzo** [comment]
Thanks for the quick response! I'll let you know if we find any issue.
